[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'pkg-config', 'mysql80', 'gcc', 'gfortran', 'libffi', 'openssl']

[phases.install]
cmds = [
  'python -m pip install --upgrade pip',
  'pip install --no-cache-dir -r requirements.txt'
]

[phases.build]
cmds = ['python manage.py collectstatic --noinput --clear']

[start]
cmd = 'python manage.py migrate && gunicorn main_project.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120'