# Generated by Django 4.0.7 on 2022-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cement', models.CharField(max_length=200)),
                ('sand', models.CharField(max_length=200)),
                ('aggregate', models.CharField(max_length=200)),
                ('steel', models.CharField(max_length=200)),
                ('paint', models.CharField(max_length=200)),
                ('bricks', models.CharField(max_length=200)),
                ('tiles', models.CharField(max_length=200)),
            ],
        ),
    ]
