# Generated by Django 4.0.7 on 2022-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0002_materialdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetails',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
