# Generated by Django 4.0.7 on 2022-09-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0003_materialdetails_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetails',
            name='supply_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
