# Generated by Django 4.0.7 on 2022-09-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0004_materialdetails_supply_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetails',
            name='send_from_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
