# Generated by Django 4.0.7 on 2022-09-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0005_materialdetails_send_from_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetails',
            name='land',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
