# Generated by Django 4.0.7 on 2022-09-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0006_materialdetails_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdetails',
            name='aggregate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materialdetails',
            name='bricks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materialdetails',
            name='cement',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materialdetails',
            name='land',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materialdetails',
            name='paint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materialdetails',
            name='sand',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materialdetails',
            name='steel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materialdetails',
            name='tiles',
            field=models.IntegerField(null=True),
        ),
    ]
