# Generated by Django 4.0.7 on 2022-09-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0007_alter_materialdetails_aggregate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetails',
            name='send_to_analyse',
            field=models.BooleanField(default=False),
        ),
    ]
