# Generated by Django 4.0.7 on 2022-09-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInitiationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('contact', models.PositiveBigIntegerField()),
                ('building_type', models.CharField(max_length=200)),
                ('land_area', models.CharField(max_length=200)),
                ('soil_type', models.CharField(max_length=200)),
                ('soil_condition', models.CharField(max_length=200)),
                ('foundation', models.CharField(max_length=200)),
                ('water', models.CharField(max_length=200)),
            ],
        ),
    ]
