# Generated by Django 4.0.7 on 2022-09-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0002_customerinitiationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinitiationform',
            name='send_customer',
            field=models.BooleanField(default=False),
        ),
    ]
