# Generated by Django 4.0.7 on 2022-09-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0003_customerinitiationform_send_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinitiationform',
            name='request_estimation',
            field=models.BooleanField(default=False),
        ),
    ]
