# Generated by Django 4.0.7 on 2022-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0004_customerinitiationform_request_estimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinitiationform',
            name='cost',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
