# Generated by Django 4.0.7 on 2022-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0005_customerinitiationform_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinitiationform',
            name='price_send',
            field=models.BooleanField(default=False),
        ),
    ]
