# Generated by Django 4.0.7 on 2022-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0006_customerinitiationform_price_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinitiationform',
            name='accept_work',
            field=models.BooleanField(default=False),
        ),
    ]
